version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn -DskipTests package
      - tar -cvf output.tar ./*
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - ./target/HelloApp-0.0.1-SNAPSHOT.war